version: '3.8'
services:
  
  mysql:
    container_name: mysql-docker
    image: mysql:8.0.31
    restart: unless-stopped 
    tty: true 
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=laravel


  
